### POST
POST http://localhost:8080/api/courts
Content-Type: application/json

{
  "id": null,
  "name": "Court 8",
  "surfaceId": 2
}

### PUT
PUT http://localhost:8080/api/courts
Content-Type: application/json

{
  "id": 1,
  "name": "Court 9",
  "surfaceId":1
}

### DELETE
DELETE http://localhost:8080/api/courts/1
Content-Type: application/json

{
}

### GET
GET http://localhost:8080/api/courts/2
Content-Type: application/json

{

}

### POST
POST http://localhost:8080/api/reservations
Content-Type: application/json

{
  "courtId": 3,
  "userName": "Jozef4",
  "phoneNumber": "0903113188",
  "startTime": "2022-12-04T10:30:30",
  "endTime": "2022-12-04T10:55:30",
  "isDoubles": false
}

### PUT
PUT http://localhost:8080/api/reservations
Content-Type: application/json

{
  "id": 1,
  "courtId": 2,
  "userName": "Jozef1",
  "phoneNumber": "0903123189",
  "startTime": "2025-12-04T11:30:30",
  "endTime": "2025-12-04T11:57:30",
  "isDoubles": false
}

### DELETE
DELETE http://localhost:8080/api/reservations/1
Content-Type: application/json

{
}

### GET
GET http://localhost:8080/api/reservations/2
Content-Type: application/json

{

}