spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username:
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
server:
  servlet:
    contextPath: /api/
  port: 8080
app:
  data:
    init: true
